title: Mercy Lelago # your name (or website title) here
logo: "/images/Profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, my name is Mercy Lelago, and I am a 4th year student at Seattle Pacific University studying Computer Information Systems and Business administrations. 
  I am passionate about technology and eager to contribute to an organization both technically and culturally. 
  I am interested in product management, web development and design roles.  
  
  <br><br>
  
  <br><br>
  <a href="https://www.linkedin.com/mwlite/in/mercy-lelago/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://agile-scrubland-26896.herokuapp.com/resume.html">View My Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
