title: Mercy Lelago # your name (or website title) here
logo: "/images/Profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello everyone, I am a 4th year student at Seattle Pacific University majoring in Information Systems and minoring in Business Administrations.I am intrested in product
  managment desgin and Web development. 
  
  
  <a href="https://www.linkedin.com/in/mercy-lelago/">View My LinkedIn Profile</a> 
  
