title: Mercy Lelago # your name (or website title) here
logo: "/images/Profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello there, my name is M ercy and I am a 4th year student at Seattle Pacific University studying Computer Information Systems and Business Administrators. 
  I am passionate about technology and egar to contribute to an organization technically and culturally. I am intrested in product management, design, and 
  web development.
  
  <br><br>
  
  <br><br>
  <a href="https://www.linkedin.com/mwlite/in/mercy-lelago/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
